### ISSUE TITLE
TypeError thrown from non-native Elm code (in elm-test)

### ISSUE THREAD

**Issue by rhofour** [elm-lang/core#935]
Issue originally detailed at: https://github.com/elm-community/elm-test/issues/227

Summary: I'm able to trigger a type error
> This test failed because it threw an exception: "TypeError: shrink1 is not a function"

in my tests in both the Node and HTML runners. The offending commit is: https://github.com/rhofour/elm-comidi/commit/0d62c8ff4ce526a33b2aa424118bec4eaef261a2 . Before this commit the tests pass and afterwards they fail with the above error.

This is on Elm 0.18. The exact-dependencies.json for my tests is:

>     "elm-community/lazy-list": "1.0.0",
>     "elm-community/elm-test": "4.2.0",
>     "elm-community/shrink": "2.0.0",
>     "elm-lang/virtual-dom": "2.0.4",
>     "eeue56/elm-lazy": "1.0.0",
>     "mgold/elm-random-pcg": "5.0.2",
>     "elm-lang/lazy": "2.0.0",
>     "eeue56/elm-lazy-list": "1.0.0",
>     "elm-lang/html": "2.0.0",
>     "eeue56/elm-shrink": "1.0.0",
>     "Bogdanp/elm-combine": "3.1.1",
>     "elm-lang/core": "5.1.1"

I'm on Fedora 27 with Google Chrome 63.0.3239.108 (64-bit).

**Comment by evancz** [comment]
I need issues with an http://sscce.org to do anything. I cannot be the one sorting through 12 dependencies and a whole application repo to figure out **if** my code is responsible here.

@rtfeldman and others in that thread, when you get issues like the original `elm-test` one, can you either (1) tell people what is expected before passing them to me or (2) do the work that needs to be done for it to be a viable issue.

Please someone open this again once it has been pinned down to an SSCCE that demonstrates the issue is actually in `elm-lang/core` or in `elm-lang/elm-compiler`.
