### ISSUE TITLE
Core 4.0.4 Breaks Elm Reactor

### ISSUE THREAD

**Issue by Kwarrtz** [elm-lang/core#688]
After updating from core v4.0.3 to v4.0.4, my programs stopped working in the reactor. The program select screen worked fine, but when I went to run my program, it just displayed a blank screen. Pulling up the element inspector, I found that the body tag was empty and there were two errors on my JS console.

```
Uncaught ReferenceError: _elm_lang$core$Json_Encode$string is not defined
Uncaught TypeError: runElmProgram is not a function
```

Reverting to core 4.0.3 fixed the issue.

I am running Elm 0.17.1 on Chrome v54 and Mac OS X Yosemite.

**Comment by evancz** [comment]
Can you try deleting the `elm-stuff/` directory and trying again? What happens?

**Comment by Kwarrtz** [comment]
Ah! That solved it.

Thank you.
